# -*- coding: utf-8 -*-
"""Operadores Aritméticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XE4kXMpmdy5S_vel5yQ2XvFpePahwMI_

#### **Python Fundamneto**
*by [Veja aqui](https://www.learnpython.org/pt/Operadores_b%C3%A1sicos)*

---

## Operadores Aritméticos

<center><img alt="Math" width="35%" src="https://image.freepik.com/free-psd/flat-lay-pi-sign-mathematics_23-2148458911.jpg"></center>


Nesta aula, vou te mostrar quais são os operadores aritméticos do Python, além da sua ordem de precedência quando compondo uma expressão matemática.

Os operadores aritméticos do Python são:

* `+` Adição
* `-` Subtração
* `*` Multiplicação
* `/` Divisão
* `**` Exponenciação
* `//` Divisão (resultado inteiro)

Abaixo, podemos ver exemplos de uso desses operadores.
"""

# adição
13 + 45 + 89 + 90

# subtração
87 - 700

# multiplicação
7 * 10

# divisão
70 / 3

# divisão (resultado inteiro)
70 // 3

"""$$
7^2
$$
"""

# exponenciação
7 ** 2

"""## Ordem de precedência

Se já faz um tempo desde o seu último contato com a matemática, vale a pena relembrarmos a ordem correta das operações matemáticas.

$$
\begin{aligned}
x & = 3 + 10 * 3 \\
x & = 3 + (10 * 3) \\
x & = 3 + 30 \\
x & = 33
\end{aligned}
$$

Lembre-se que a ordem das operações matemáticas é:

* 1º Parêntesis;
* 2º Expoentes;
* 3º Multiplicações e Divisões; (da esquerda para a direita)
* 4º Somas e Subtrações. (da esquerda para a direita)

Vamos ver como isso funciona na prática com Python.
"""

# primeiro é resolvida a multiplicação e depois a subtração
10 * 3

# multiplicamos, e depois somamos o resultado
3 + 30

"""Mesmo acrescentando um pouquinho mais de complexidade, o Python consegue lidar com extrema facilidade, cabendo a nós termos atenção às operações realizadas.

$$
\begin{aligned}
x & = 5 + 9 - 2^2 + \frac{9}{3} \\
x & = 5 + 9 - 4 + \frac{9}{3} \\
x & = 5 + 9 - 4 + 3 \\
x & = 14 - 4 + 3 \\
x & = 10 + 3 \\
x & = 13 \\
\end{aligned}
$$


"""

# resolução da equação acima usando Python
5 + 9 - 2**2 + 9/3

5 + 9 - (2**2) + (9/3)

"""Expressões maiores podem confundir, então o segredo é anotar a correta ordem de execução das operações matemáticas:

1. Parêntesis
2. Expoentes
3. Multiplicações e Divisões (esquerda para a direita)
4. Somas e subtrações (esquerda para a direita)

#### Exemplo 1

Calcula a média simples das notas das 3 provas de matemática
* Nota 1 = 8,5
* Nota 2 = 9,2
* Nota 3 = 7,5
"""

# resposta
(8.5 + 9.2 + 7.5) / 3

"""#### Exemplo 2

Qual a área de 

* O volume de uma esfera é calculada por meio da expressão $V = \frac{4}{3} \pi r^3$.
* Calcule o volume de uma esfera de 5 metros?
"""

# resposta
4/3 * 3.14 * 5 ** 3

# resposta
(4/3) * (3.14) * (5 ** 3)